import { test, expect } from '@playwright/test';
test('weekly brief is local, holds incomplete export and resets review after editing', async ({ context, page, baseURL }) => {
  if (!baseURL?.startsWith('http://localhost:')) throw new Error('Weekly contract requires localhost');
  const session = { access_token: 'fixture.header.signature', refresh_token: 'fixture', token_type: 'bearer', expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: 'fixture-owner', email: 'info@true-color.ca' } };
  await context.addCookies([{ name: `sb-${new URL(process.env.NEXT_PUBLIC_SUPABASE_URL ?? 'https://example.supabase.co').hostname.split('.')[0]}-auth-token`, value: 'base64-' + Buffer.from(JSON.stringify(session)).toString('base64url'), url: baseURL }]);
  const mutations: string[] = [];
  await page.route('**/api/staff/**', route => { if (route.request().method() !== 'GET') mutations.push(route.request().url()); return route.fulfill({ json: [] }); });
  await page.goto('/staff/social/weekly');
  await page.getByLabel('First day').fill('2026-09-30');
  await page.getByRole('button', { name: 'Start seven-day plan' }).click();
  const day = page.locator('article').first();
  await day.getByLabel('Posting day').check();
  await day.getByLabel('Theme', { exact: true }).fill('Finished work');
  await day.getByLabel('Audience', { exact: true }).fill('Local shops');
  await day.getByLabel('Objective', { exact: true }).fill('See print detail');
  await page.getByRole('button', { name: 'Export for monthly review' }).click();
  await expect(page.getByRole('status')).toContainText('Attach a completed creative');
  await page.getByLabel('I checked that the completed creative package is for True Color.').check();
  const creative = { id: '11111111-1111-4111-8111-111111111111', title: 'Print details', scheduleTime: '2026-09-30T16:00:00Z', channels: ['facebook'], captionFacebook: 'Finished print.', captionInstagram: '', imageFilename: 'real.jpg', imageSha256: 'a'.repeat(64) };
  await page.getByLabel('Completed creative package', { exact: true }).setInputFiles({ name: 'week.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ schemaVersion: 1, kind: 'truecolor-month-plan', title: 'Test', creatives: [creative] })) });
  await day.getByLabel('I reviewed this creative against the day’s brief.').check();
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export for monthly review' }).click();
  expect((await download).suggestedFilename()).toBe('truecolor-review-2026-09-30.json');
  await day.getByLabel('Theme', { exact: true }).fill('Updated theme');
  await expect(day.getByLabel('I reviewed this creative against the day’s brief.')).not.toBeChecked();
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(mutations).toEqual([]);
});
