import { test, expect } from '@playwright/test';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname,join } from 'node:path';
test('bounded prepared batch reaches draft save with stable creative IDs and no approval or dispatch', async ({ context,page,baseURL }) => {
  if (!baseURL?.startsWith('http://localhost:')) throw new Error('Harness rehearsal requires localhost');
  const session={access_token:'fixture.header.signature',refresh_token:'fixture',token_type:'bearer',expires_at:Math.floor(Date.now()/1000)+3600,user:{id:'fixture-owner',email:'info@true-color.ca'}};
  await context.addCookies([{name:`sb-${new URL(process.env.NEXT_PUBLIC_SUPABASE_URL ?? 'https://example.supabase.co').hostname.split('.')[0]}-auth-token`,value:'base64-'+Buffer.from(JSON.stringify(session)).toString('base64url'),url:baseURL}]);
  const writes: string[]=[];const saves: Record<string,unknown>[]=[];
  await page.route('**/api/staff/**',route=>{if(route.request().method()!=='GET')writes.push(route.request().url());return route.fulfill({json:[]});});
  await page.route('**/api/staff/social/batch/monthly*',route=>{
    if(route.request().method()==='GET')return route.fulfill({json:{businessId:'truecolor-fixture',batches:[],hasMore:false}});
    saves.push(route.request().postDataJSON());return route.fulfill({json:{created:6,logicalPosts:3,posts:[]}});
  });
  let uploads=0;
  await page.route('**/api/staff/social/upload',route=>{uploads++;return route.fulfill({json:{url:`https://example.com/image-${uploads}.jpg`}});});
  await page.route('https://example.com/**',route=>route.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZioAAAAASUVORK5CYII=','base64')}));
  const privatePlan=process.env.HARNESS_REHEARSAL_PLAN ? JSON.parse(readFileSync(process.env.HARNESS_REHEARSAL_PLAN,'utf8')) : null;
  const files=privatePlan ? privatePlan.creatives.map((c: {imageFilename:string})=>({name:c.imageFilename,mimeType:c.imageFilename.endsWith('.jpg')?'image/jpeg':'image/png',buffer:readFileSync(join(dirname(process.env.HARNESS_REHEARSAL_PLAN!),'images',c.imageFilename))})) : [1,2,3].map(n=>({name:`sample-${n}.png`,mimeType:'image/png',buffer:Buffer.from(`synthetic-file-${n}`)}));
  const creatives=privatePlan?.creatives ?? files.map((f: {name:string;buffer:Buffer},i:number)=>({id:`${i+1}`.repeat(8)+'-1111-4111-8111-111111111111',title:`Sample ${i+1}`,scheduleTime:`2026-09-${10+i}T14:00:00-06:00`,channels:['facebook','instagram'],captionFacebook:`Sample ${i+1}. #TrueColorPrinting #SaskatoonPrintShop`,captionInstagram:`Sample ${i+1}. #TrueColorPrinting #SaskatoonPrintShop`,imageFilename:f.name,imageSha256:createHash('sha256').update(f.buffer).digest('hex')}));
  await page.goto('/staff/social/monthly');
  await page.getByLabel('Prepared plan JSON').setInputFiles({name:'month-plan.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:1,kind:'truecolor-month-plan',title:'Harness rehearsal',creatives}))});
  await page.getByLabel('Matching original image files').setInputFiles(files);
  expect(uploads).toBe(0);expect(saves).toHaveLength(0);
  await page.getByRole('button',{name:'Upload photos into preparation',exact:true}).click();
  await expect(page.getByText('Prepared month loaded.',{exact:false})).toBeVisible();
  expect(uploads).toBe(3);expect(saves).toHaveLength(0);
  await page.getByRole('button',{name:'Save drafts in chunks',exact:true}).click();
  await expect(page.getByRole('link',{name:/Review saved batch/})).toBeVisible();
  expect(saves).toHaveLength(1);
  const posts=saves[0].posts as Record<string,unknown>[];
  expect(posts.map(p=>p.creative_id)).toEqual(creatives.map((c:{id:string})=>c.id));
  expect(posts.map(p=>p.caption_facebook)).toEqual(creatives.map((c:{captionFacebook:string})=>c.captionFacebook));
  expect(posts[0].schedule_time).toBe(new Date(creatives[0].scheduleTime).toISOString());
  expect(posts.every(p=>!('approval_hash' in p))).toBe(true);
  await page.reload();
  await page.getByRole('button',{name:'Resume chunk save',exact:true}).click();
  expect(saves).toHaveLength(1);expect(writes).toEqual([]);
  if(process.env.HARNESS_REHEARSAL_SCREENSHOT) await page.screenshot({path:process.env.HARNESS_REHEARSAL_SCREENSHOT,fullPage:true});
});
