import { describe, expect, it, vi, beforeEach } from "vitest";
import { NextResponse } from "next/server";
import { parseLibraryCatalog, libraryReviewLabel } from "../asset-library";
const mocks = vi.hoisted(() => ({ auth: vi.fn(), service: vi.fn() }));
vi.mock("@/lib/supabase/server", () => ({ requireStaffUser: mocks.auth, createServiceClient: mocks.service }));
import { GET } from "@/app/api/staff/social/library/route";
const asset = { id: "photo-1", sha256: "a".repeat(64), storagePath: "originals/photo.jpg", filename: "photo.jpg", title: "Sign", description: "Shop sign", alt: "Sign", category: "signs", kind: "photo", sourceUrl: "https://truecolorprinting.ca/photo.jpg", sourcePage: "https://truecolorprinting.ca/gallery", sourceType: "website-gallery", width: 800, height: 600, bytes: 1234, rightsStatus: "hold", privacyStatus: "review-required", sourcePublished: true, tags: ["signs"] };
const catalog = () => ({ schemaVersion: 1, businessId: "truecolor", collectedAt: "2026-09-06T00:00:00Z", assets: [{ ...asset }] });
describe("asset library", () => {
  beforeEach(() => vi.resetAllMocks());
  it("preserves hold even for an already published source", () => { const result = parseLibraryCatalog(catalog()); expect(result.assets[0].rightsStatus).toBe("hold"); expect(libraryReviewLabel(result.assets[0])).toBe("Held — do not use"); });
  it.each([{ storagePath: "originals/../secret" }, { sourceUrl: "javascript:alert(1)" }, { sourceUrl: "https://example.com/p?token=secret" }, { rightsStatus: "approved" }, { width: 0 }])("rejects invalid or unsafe asset fields %o", update => { const c = catalog(); Object.assign(c.assets[0], update); expect(() => parseLibraryCatalog(c)).toThrow(); });
  it("drops unknown private metadata", () => { const c = catalog(); Object.assign(c.assets[0], { localPath: "/private/file" }); expect(parseLibraryCatalog(c).assets[0]).not.toHaveProperty("localPath"); });
  it("rejects duplicate IDs and other business catalogs", () => { const c = catalog(); c.assets.push({ ...asset }); expect(() => parseLibraryCatalog(c)).toThrow(); expect(() => parseLibraryCatalog({ ...catalog(), businessId: "other" })).toThrow(); });
  it.each([401, 403])("requires staff before storage access (%s)", async status => { mocks.auth.mockResolvedValue(NextResponse.json({ error: "Denied" }, { status })); expect((await GET()).status).toBe(status); expect(mocks.service).not.toHaveBeenCalled(); });
  it("rejects a public bucket before downloading", async () => { mocks.auth.mockResolvedValue({}); const from = vi.fn(); mocks.service.mockReturnValue({ storage: { getBucket: vi.fn().mockResolvedValue({ data: { public: true } }), from } }); expect((await GET()).status).toBe(503); expect(from).not.toHaveBeenCalled(); });
  it("provides a clear missing catalog state", async () => { mocks.auth.mockResolvedValue({}); mocks.service.mockReturnValue({ storage: { getBucket: vi.fn().mockResolvedValue({ data: { public: false } }), from: () => ({ download: vi.fn().mockResolvedValue({ error: {} }) }) } }); const r = await GET(); expect(r.status).toBe(200); expect((await r.json()).state).toBe("unavailable"); });
  it("returns staff signed previews without raw storage paths or public URL creation", async () => { mocks.auth.mockResolvedValue({}); const createSignedUrls = vi.fn().mockResolvedValue({ data: [{ path: asset.storagePath, signedUrl: "https://storage.example/signed" }] }); mocks.service.mockReturnValue({ storage: { getBucket: vi.fn().mockResolvedValue({ data: { public: false } }), from: () => ({ download: vi.fn().mockResolvedValue({ data: new Blob([JSON.stringify(catalog())]) }), createSignedUrls }) } }); const response = await GET(); const body = await response.json(); expect(response.headers.get("cache-control")).toBe("private, no-store"); expect(body.assets[0].storagePath).toBeUndefined(); expect(body.assets[0].previewUrl).toBe("https://storage.example/signed"); expect(body.assets[0].rightsStatus).toBe("hold"); expect(createSignedUrls).toHaveBeenCalledWith([asset.storagePath], 900); });
});
