/** Standalone private HTML: no site layout, trackers, scripts, forms or approval authority. */
export interface HtmlPreview {
 businessName: string; imageUrl: string; captions: {instagram: string; facebook: string};
 scheduleTime: string; status: string; revision: number; mediaTreatment: string; expiresAt: string;
}
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function previewHtml(p: HtmlPreview) {
 const date = new Date(p.scheduleTime);
 const schedule = Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat('en-CA', {timeZone:'America/Regina',dateStyle:'full',timeStyle:'short'}).format(date) : 'Choose a posting date';
 const card = (platform: 'instagram'|'facebook') => `<article class="post ${platform}"><div class="platform">${platform === 'instagram' ? 'Instagram' : 'Facebook'} <span>Feed preview</span></div><div class="identity"><div class="avatar">${escape(p.businessName.slice(0,1))}</div><div><strong>${escape(p.businessName)}</strong><small>Proposed post · ${escape(p.status)}</small></div><span class="dots" aria-hidden="true">•••</span></div><img src="${escape(p.imageUrl)}" alt="Prepared photograph for ${platform}" referrerpolicy="no-referrer"><div class="caption">${escape(p.captions[platform])}</div><footer>${platform === 'instagram' ? '♡ &nbsp; ◯ &nbsp; ↗' : 'Like &nbsp; · &nbsp; Comment &nbsp; · &nbsp; Share'}</footer></article>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><title>Review your post</title><style>
 *{box-sizing:border-box}body{margin:0;background:#f4f1ec;color:#211c17;font-family:ui-sans-serif,system-ui,sans-serif}main{max-width:1060px;margin:auto;padding:36px 22px 60px}.eyebrow{font-size:11px;letter-spacing:.15em;text-transform:uppercase;color:#a0442b;font-weight:700}h1{font-family:Georgia,serif;font-size:clamp(32px,6vw,54px);font-weight:400;letter-spacing:-.035em;margin:12px 0}header p{max-width:650px;line-height:1.6;color:#625c54}.schedule{padding:16px 20px;background:#e8e1d7;border-left:3px solid #b94729;margin:24px 0 28px;line-height:1.6}.schedule small{display:block;color:#635c54}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:start}.post{overflow:hidden;border:1px solid #d6d0c7;border-radius:14px;background:white;box-shadow:0 8px 28px #392b1810}.platform{padding:14px 18px;border-bottom:1px solid #eee;font-weight:750}.platform span{float:right;font-size:11px;color:#807970;font-weight:400}.identity{padding:17px;display:flex;align-items:center;gap:10px}.identity small{display:block;font-size:11px;margin-top:4px;color:#777}.avatar{display:grid;place-items:center;width:36px;height:36px;border-radius:50%;background:#c83e2a;color:white;font-family:Georgia,serif;font-size:21px}.dots{margin-left:auto;color:#777}.post img{width:100%;height:auto;display:block;background:#eee}.caption{padding:18px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px;line-height:1.65}.post footer{border-top:1px solid #eee;padding:14px 18px;color:#777;font-size:13px}.note{font-size:12px;line-height:1.65;color:#736b61;margin-top:24px}.action{background:#211c17;color:#fff;padding:20px;border-radius:12px;margin-top:28px;line-height:1.6}.action strong{display:block;margin-bottom:4px}@media(max-width:700px){main{padding:25px 14px}.grid{grid-template-columns:1fr;gap:24px}}
 </style></head><body><main><header><div class="eyebrow">Private review · Version ${escape(p.revision)}</div><h1>Ready for a closer look.</h1><p>Here is the prepared photo and the exact caption for each destination. These are approximate feed layouts; platform styling may differ.</p></header><div class="schedule"><strong>${escape(schedule)}</strong><small>America/Regina · ${escape(p.mediaTreatment)} · ${escape(p.status)}</small></div><section class="grid">${card('instagram')}${card('facebook')}</section><div class="action"><strong>Happy with the image, captions and date?</strong>Return to Telegram and tap Approve. To change anything, use the edit buttons there. Opening this preview does not approve or publish the post.</div><p class="note">This private link expires at ${escape(p.expiresAt)}. No engagement figures are simulated. Your original photo remains preserved separately.</p></main></body></html>`;
}
